# Intrduction to NumPy


#### 1. Import NumPy under the name np.

In [1]:
# your code here
import numpy as np

#### 2. Print your NumPy version.

In [2]:
# your code here
np.version.version

'1.17.2'

#### 3. Generate a 2x3x5 3-dimensional array with random values. Assign the array to variable *a*.
**Challenge**: there are at least three easy ways that use numpy to generate random arrays. How many ways can you find?

In [7]:
# Method 1
a = np.random.random((2,3,5))

In [ ]:
# Method 2
a= numpy.random.rand((2,3,5))

In [5]:
# Method 3
a = np.random.randint(10, size=(2,3,5))

#### 4. Print *a*.


In [9]:
# your code here
a

array([[[0.08351394, 0.10443824, 0.47954567, 0.05416233, 0.57457901],
        [0.4954182 , 0.06192178, 0.09421582, 0.27411533, 0.87316135],
        [0.93420911, 0.82977764, 0.97152657, 0.32986716, 0.08750241]],

       [[0.63314441, 0.22519863, 0.86644823, 0.50808074, 0.687646  ],
        [0.58493186, 0.29333028, 0.30365684, 0.81179789, 0.00504721],
        [0.87238915, 0.52665174, 0.39707643, 0.73124302, 0.72083303]]])

#### 5. Create a 5x2x3 3-dimensional array with all values equaling 1. Assign the array to variable *b*.

In [11]:
# your code here
b = np.ones((5,2,3))

#### 6. Print *b*.


In [12]:
# your code here
b

array([[[1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.]]])

#### 7. Do *a* and *b* have the same size? How do you prove that in Python code?

In [13]:
# your code here
a.shape == b.shape

False

#### 8. Are you able to add *a* and *b*? Why or why not?


In [17]:
# your answer here
# a and b can't be added because they do not have the same shape.

#### 9. Transpose *b* so that it has the same structure of *a* (i.e. become a 2x3x5 array). Assign the transposed array to variable *c*.

In [37]:
c = np.transpose(b,axes=(1,2,0))
c.shape

(2, 3, 5)

#### 10. Try to add *a* and *c*. Now it should work. Assign the sum to variable *d*. But why does it work now?

In [80]:
# your code/answer here
d = np.add(a,c)
# a and c now have the same shape

#### 11. Print *a* and *d*. Notice the difference and relation of the two array in terms of the values? Explain.

In [45]:
# your code/answer here
print(a)
print('\n')
print(d)

[[[0.08351394 0.10443824 0.47954567 0.05416233 0.57457901]
  [0.4954182  0.06192178 0.09421582 0.27411533 0.87316135]
  [0.93420911 0.82977764 0.97152657 0.32986716 0.08750241]]

 [[0.63314441 0.22519863 0.86644823 0.50808074 0.687646  ]
  [0.58493186 0.29333028 0.30365684 0.81179789 0.00504721]
  [0.87238915 0.52665174 0.39707643 0.73124302 0.72083303]]]


[[[1.08351394 1.10443824 1.47954567 1.05416233 1.57457901]
  [1.4954182  1.06192178 1.09421582 1.27411533 1.87316135]
  [1.93420911 1.82977764 1.97152657 1.32986716 1.08750241]]

 [[1.63314441 1.22519863 1.86644823 1.50808074 1.687646  ]
  [1.58493186 1.29333028 1.30365684 1.81179789 1.00504721]
  [1.87238915 1.52665174 1.39707643 1.73124302 1.72083303]]]


#### 12. Multiply *a* and *c*. Assign the result to *e*.

In [49]:
# your code here
e = np.multiply(a,c)

#### 13. Does *e* equal to *a*? Why or why not?


In [55]:
# your code/answer here
# Yes, because a is composed of '1' elements only

#### 14. Identify the max, min, and mean values in *d*. Assign those values to variables *d_max*, *d_min* and *d_mean*.

In [83]:
# your code here
d_max = d.max()
d_min = d.min()
d_mean = d.mean()

#### 15. Now we want to label the values in *d*. First create an empty array *f* with the same shape (i.e. 2x3x5) as *d* using `np.empty`.


In [64]:
# your code here
f = np.empty((2,3,5))

#### 16. Populate the values in *f*. 

For each value in *d*, if it's larger than *d_min* but smaller than *d_mean*, assign 25 to the corresponding value in *f*. If a value in *d* is larger than *d_mean* but smaller than *d_max*, assign 75 to the corresponding value in *f*. If a value equals to *d_mean*, assign 50 to the corresponding value in *f*. Assign 0 to the corresponding value(s) in *f* for *d_min* in *d*. Assign 100 to the corresponding value(s) in *f* for *d_max* in *d*. In the end, f should have only the following values: 0, 25, 50, 75, and 100.

**Note**: you don't have to use Numpy in this question.

In [87]:
# your code here

def change_value_to_int(x):
    if d_min<x<d_mean:
        x=25
    elif d_mean<x<d_max:
        x=75
    elif x==d_mean:
        x=50
    elif x==d_min:
        x=0
    elif x==d_max:
        x=100
    return x

for i in range(len(d)):
    for j in range(len(d[i])):
        for k in range(len(d[i][j])):
            f[i][j][k]= change_value_to_int(d[i][j][k])

#### 17. Print *d* and *f*. Do you have your expected *f*?
For instance, if your *d* is:
```python
[[[1.85836099, 1.67064465, 1.62576044, 1.40243961, 1.88454931],
[1.75354326, 1.69403643, 1.36729252, 1.61415071, 1.12104981],
[1.72201435, 1.1862918 , 1.87078449, 1.7726778 , 1.88180042]],
[[1.44747908, 1.31673383, 1.02000951, 1.52218947, 1.97066381],
[1.79129243, 1.74983003, 1.96028037, 1.85166831, 1.65450881],
[1.18068344, 1.9587381 , 1.00656599, 1.93402165, 1.73514584]]]
```
Your *f* should be:
```python
[[[ 75.,  75.,  75.,  25.,  75.],
[ 75.,  75.,  25.,  25.,  25.],
[ 75.,  25.,  75.,  75.,  75.]],
[[ 25.,  25.,  25.,  25., 100.],
[ 75.,  75.,  75.,  75.,  75.],
[ 25.,  75.,   0.,  75.,  75.]]]
```

In [89]:
# your code here
print(d)
print('\n')
print(f)

[[[1.08351394 1.10443824 1.47954567 1.05416233 1.57457901]
  [1.4954182  1.06192178 1.09421582 1.27411533 1.87316135]
  [1.93420911 1.82977764 1.97152657 1.32986716 1.08750241]]

 [[1.63314441 1.22519863 1.86644823 1.50808074 1.687646  ]
  [1.58493186 1.29333028 1.30365684 1.81179789 1.00504721]
  [1.87238915 1.52665174 1.39707643 1.73124302 1.72083303]]]


[[[ 25.  25.  25.  25.  75.]
  [ 75.  25.  25.  25.  75.]
  [ 75.  75. 100.  25.  25.]]

 [[ 75.  25.  75.  75.  75.]
  [ 75.  25.  25.  75.   0.]
  [ 75.  75.  25.  75.  75.]]]


#### 18. Bonus question: instead of using numbers (i.e. 0, 25, 50, 75, and 100), use string values  ("A", "B", "C", "D", and "E") to label the array elements. For the example above, the expected result is:

```python
[[[ 'D',  'D',  'D',  'B',  'D'],
[ 'D',  'D',  'B',  'B',  'B'],
[ 'D',  'B',  'D',  'D',  'D']],
[[ 'B',  'B',  'B',  'B',  'E'],
[ 'D',  'D',  'D',  'D',  'D'],
[ 'B',  'D',   'A',  'D', 'D']]]
```
**Note**: you don't have to use Numpy in this question.

In [91]:
# your code here

f = f.astype(str)

def change_value_to_str(x):
    if d_min<x<d_mean:
        x='B'
    elif d_mean<x<d_max:
        x='D'
    elif x==d_mean:
        x='C'
    elif x==d_min:
        x='A'
    elif x==d_max:
        x='E'
    return x

for i in range(len(d)):
    for j in range(len(d[i])):
        for k in range(len(d[i][j])):
            f[i][j][k]= change_value_to_str(d[i][j][k])